name: SMW Mediawiki Image Build

on:
  push:
    branches:
      - 'smw'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get next version
        uses: reecetech/version-increment@2023.4.1
        id: version
        with:
          scheme: calver
          increment: patch
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: starcitizentools/mediawiki:smw-latest,starcitizentools/mediawiki:smw-${{ steps.version.outputs.version }}
